attributes:
  LastSwiftUpdateCheck: 1010
  LastUpgradeCheck: 1010
  ORGANIZATIONNAME: Yoki Higashihara
configs:
  Debug: debug
  Release: release
name: ReadingList
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      CODE_SIGN_IDENTITY: iPhone Developer
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CODE_SIGN_IDENTITY: iPhone Developer
      GCC_OPTIMIZATION_LEVEL: 0
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  ReadingList:
    dependencies:
    - sdk: WebKit.framework
    - framework: Pods_ReadingList.framework
    platform: iOS
    postbuildScripts:
    - inputFiles:
      - ${PODS_PODFILE_DIR_PATH}/Podfile.lock
      - ${PODS_ROOT}/Manifest.lock
      name: '[CP] Check Pods Manifest.lock'
      outputFiles:
      - $(DERIVED_FILE_DIR)/Pods-ReadingList-checkManifestLockResult.txt
      runOnlyWhenInstalling: false
      script: "diff \"${PODS_PODFILE_DIR_PATH}/Podfile.lock\" \"${PODS_ROOT}/Manifest.lock\"
        > /dev/null\nif [ $? != 0 ] ; then\n    # print error to STDERR\n    echo
        \"error: The sandbox is not in sync with the Podfile.lock. Run 'pod install'
        or update your CocoaPods installation.\" >&2\n    exit 1\nfi\n# This output
        is used by Xcode 'outputs' to avoid re-running this script phase.\necho \"SUCCESS\"
        > \"${SCRIPT_OUTPUT_FILE_0}\"\n"
      shell: /bin/sh
      showEnvVars: false
    - runOnlyWhenInstalling: false
      script: 'if [ $CONFIGURATION = "Debug" ]; then

        ${PODS_ROOT}/LicensePlist/license-plist --output-path $PRODUCT_NAME/Settings.bundle

        fi

        '
      shell: /bin/sh
    - inputFileLists:
      - ${PODS_ROOT}/Target Support Files/Pods-ReadingList/Pods-ReadingList-frameworks-${CONFIGURATION}-input-files.xcfilelist
      name: '[CP] Embed Pods Frameworks'
      outputFileLists:
      - ${PODS_ROOT}/Target Support Files/Pods-ReadingList/Pods-ReadingList-frameworks-${CONFIGURATION}-output-files.xcfilelist
      runOnlyWhenInstalling: false
      script: '"${PODS_ROOT}/Target Support Files/Pods-ReadingList/Pods-ReadingList-frameworks.sh"

        '
      shell: /bin/sh
      showEnvVars: false
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_ENTITLEMENTS: ReadingList/ReadingList.entitlements
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: EAZT2D654U
          INFOPLIST_FILE: ReadingList/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 11.0
          PRODUCT_BUNDLE_IDENTIFIER: yyokii.ReadingList
          PROVISIONING_PROFILE_SPECIFIER: 
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_ENTITLEMENTS: ReadingList/ReadingList.entitlements
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: EAZT2D654U
          INFOPLIST_FILE: ReadingList/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 11.0
          PRODUCT_BUNDLE_IDENTIFIER: yyokii.ReadingList
          PROVISIONING_PROFILE_SPECIFIER: 
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1
    sources:
    - ReadingList/AppDelegate.swift
    - name: Constants
      path: ReadingList/Constants
    - ReadingList/DB/Entity/ReadingItem.swift
    - ReadingList/DB/RealmManager.swift
    - ReadingList/DB/UserDefaultManager.swift
    - name: Extension
      path: ReadingList/Extension
    - ReadingList/GoogleService-Info.plist
    - ReadingList/Settings.bundle
    - name: Support
      path: ReadingList/Support
    - ReadingList/UI/AboutApp/AboutApp.storyboard
    - ReadingList/UI/AboutApp/AboutAppVC.swift
    - ReadingList/UI/AboutApp/Component/AboutAppTableViewCell.swift
    - ReadingList/UI/AboutApp/Component/AboutAppTableViewCell.xib
    - ReadingList/UI/AboutApp/Component/SwitchBtnTableViewCell.swift
    - ReadingList/UI/AboutApp/Component/SwitchBtnTableViewCell.xib
    - name: ArticleWebView
      path: ReadingList/UI/ArticleWebView
    - name: ArticleView
      path: ReadingList/UI/CustomView/ArticleView
    - ReadingList/UI/CustomView/GradationView.swift
    - name: GraphView
      path: ReadingList/UI/CustomView/GraphView
    - ReadingList/UI/CustomView/Indicator.swift
    - ReadingList/UI/CustomView/Indicator.xib
    - name: NoContentView
      path: ReadingList/UI/CustomView/NoContentView
    - name: OptionDialog
      path: ReadingList/UI/CustomView/OptionDialog
    - name: TutorialDialog
      path: ReadingList/UI/CustomView/TutorialDialog
    - name: WebTooBar
      path: ReadingList/UI/CustomView/WebTooBar
    - name: DeletedList
      path: ReadingList/UI/DeletedList
    - name: FloatingView
      path: ReadingList/UI/FloatingView
    - ReadingList/UI/Home/Home.storyboard
    - ReadingList/UI/Home/HomeModel.swift
    - ReadingList/UI/Home/HomePresenter.swift
    - ReadingList/UI/Home/HomeVC.swift
    - name: ReadingList
      path: ReadingList/UI/ReadingList
    - name: TodayDelete
      path: ReadingList/UI/TodayDelete
    - name: Utility
      path: ReadingList/Utility
    type: application
  ShareExtension:
    dependencies:
    - framework: Pods_ShareExtension.framework
    platform: iOS
    postbuildScripts:
    - inputFiles:
      - ${PODS_PODFILE_DIR_PATH}/Podfile.lock
      - ${PODS_ROOT}/Manifest.lock
      name: '[CP] Check Pods Manifest.lock'
      outputFiles:
      - $(DERIVED_FILE_DIR)/Pods-ShareExtension-checkManifestLockResult.txt
      runOnlyWhenInstalling: false
      script: "diff \"${PODS_PODFILE_DIR_PATH}/Podfile.lock\" \"${PODS_ROOT}/Manifest.lock\"
        > /dev/null\nif [ $? != 0 ] ; then\n    # print error to STDERR\n    echo
        \"error: The sandbox is not in sync with the Podfile.lock. Run 'pod install'
        or update your CocoaPods installation.\" >&2\n    exit 1\nfi\n# This output
        is used by Xcode 'outputs' to avoid re-running this script phase.\necho \"SUCCESS\"
        > \"${SCRIPT_OUTPUT_FILE_0}\"\n"
      shell: /bin/sh
      showEnvVars: false
    settings:
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: ShareExtension/ShareExtension.entitlements
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: EAZT2D654U
          INFOPLIST_FILE: ShareExtension/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 11.0
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@executable_path/../../Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: yyokii.ReadingList.ShareExtension
          SKIP_INSTALL: YES
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1
        Release:
          CODE_SIGN_ENTITLEMENTS: ShareExtension/ShareExtension.entitlements
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: EAZT2D654U
          INFOPLIST_FILE: ShareExtension/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 11.0
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@executable_path/../../Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: yyokii.ReadingList.ShareExtension
          SKIP_INSTALL: YES
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1
    sources:
    - name: Constants
      path: ReadingList/Constants
    - ReadingList/DB/UserDefaultManager.swift
    - ReadingList/Extension/Date+Extension.swift
    - ReadingList/Support/Color.xcassets
    - name: Base.lproj
      path: ShareExtension/Base.lproj
    - ShareExtension/ShareViewController.swift
    type: app-extension
